### ISSUE TITLE
Empty CSS ruleset

### ISSUE THREAD

**Issue by AvidGameFan** [AvidGameFan/dp-display#14]
Visual Studio Code complains about this line:

			.imageParagraph img { }

Apparently, it's considered bad form to have an empty CSS ruleset, although I didn't see where, as a practical matter, it should cause any problems.  Maybe document it if it's needed for a weird reason?  @Hk1020

**Comment by Hk1020** [comment]
That is just an oversight. Leftover from something that wouldn’t work. Just remove it.

**Comment by AvidGameFan** [comment]
OK, thanks!
